Video:
  Process: False
  File: test.mp4
Image:
  Process: False
  Folder: test_images
  Pattern: test
CameraCalibration:
  Folder: data/camera_cal
  Pattern: calibration
  UseStoredFile: False
  StorageFile: results/camera_cal/camCalibration.p
  ChessboardDimension: (9,6)
LaneFindingParameters:
  HlsThreshLo: 120
  HlsThreshHi: 255
  SobelXThreshLo: 50
  SobelXThreshHi: 100
