Video:
  Process: True
  InputFile:
    - data/videos/short_project_video.mp4
  StorageFolder: results/videos
Image:
  Process: False
  InputFolder: data/images
  Pattern: test
  StorageFolder: results/images
  StoreIntermediateResults: True
CameraCalibration:
  Folder: data/camera_cal
  Pattern: calibration
  UseStoredFile: True
  StorageFolder: results/camera_cal
  ChessboardDimension: (9,6), (9,5), (7,6), (7,4)
  StoreIntermediateResults: True
LaneFindingParameters:
  HlsThreshLo: 120
  HlsThreshHi: 255
  SobelXThreshLo: 50
  SobelXThreshHi: 100
