Video:
  Process: True
  InputFile:
    - data/videos/project_video.mp4
    #- data/videos/challenge_video.mp4
    #- data/videos/harder_challenge_video.mp4
  StorageFolder: results/videos
  TrackLanes: True
Image:
  Process: True
  InputFolder: data/images
  Pattern: test
  StoreIntermediateResults: True
  StorageFolder: results/images
CameraCalibration:
  Folder: data/camera_cal
  Pattern: calibration
  UseStoredFile: True
  StorageFolder: results/camera_cal
  ChessboardDimension: (9,6), (9,5), (7,6), (7,4)
  StoreIntermediateResults: False
LaneFindingParameters:
  HlsThreshLo: 140
  HlsThreshHi: 255
  SobelXThreshLo: 40
  SobelXThreshHi: 100
