Video:
  Process: True
  File: project_video.mp4
Image:
  Process: False
  Folder: test_images
  Pattern: test
CameraCalibration:
  Folder: camera_cal
  Pattern: calibration
  UseStoredFile: True
  StorageFile: camCalibration.p
  ChessboardDimension: (9,6)
LaneFindingParameters:
  HlsThreshLo: 90
  HlsThreshHi: 255
  SobelXThreshLo: 20
  SobelXThreshHi: 100
