Video:
  Process: False
  File: test.mp4
Image:
  Process: True
  Folder: test_images
  Pattern: test
CameraCalibration:
  Folder: camera_cal
  Pattern: calibration
  UseStoredFile: True
  StorageFile: camCalibration.p
  ChessboardDimension: (9,6)
LaneFindingParameters:
  HlsThreshLo: 120
  HlsThreshHi: 255
  SobelXThreshLo: 50
  SobelXThreshHi: 100
